backend = "Windows WASAPI"
bufferSizeSamples = 480

[input]
device = "Microfone (Armer Argent)"
wasapiExclusiveMode = false
wasapiAutoConvert = false
channels = 2

[output]
device = "Fones de ouvido (Armer Argent)"
wasapiExclusiveMode = false
wasapiAutoConvert = false
channels = 2
